const letterCards = [
  { front:"א", back:"Alef", examples:[{word:"אָדָם",translit:"Adam",meaning:"Homem"},{word:"אֵשׁ",translit:"Esh",meaning:"Fogo"},{word:"אֱמֶת",translit:"Emet",meaning:"Verdade"}]},
  { front:"ב", back:"Veit", examples:[{word:"לֵב",translit:"Lev",meaning:"Coração"},{word:"אָב",translit:"Av",meaning:"Pai"},{word:"טוֹב",translit:"Tov",meaning:"Bom"}]},
  { front:"בּ", back:"Beit", examples:[{word:"בֶּן",translit:"Ben",meaning:"Filho"},{word:"בַּיִת",translit:"Bayit",meaning:"Casa"},{word:"בּוֹרֵא",translit:"Bore",meaning:"Criador"}]},
  { front:"ג", back:"Gimel", examples:[{word:"גָּדוֹל",translit:"Gadol",meaning:"Grande"},{word:"גַּן",translit:"Gan",meaning:"Jardim"},{word:"גּוֹי",translit:"Goy",meaning:"Nação"}]},
  { front:"ד", back:"Dalet", examples:[{word:"דָּבָר",translit:"Davar",meaning:"Palavra"},{word:"יָד",translit:"Yad",meaning:"Mão"},{word:"דֶּרֶךְ",translit:"Derech",meaning:"Caminho"}]},
  { front:"ה", back:"Hei", examples:[{word:"הָאָרֶץ",translit:"Haaretz",meaning:"Terra"},{word:"הֵם",translit:"Hem",meaning:"Eles"},{word:"הוּא",translit:"Hu",meaning:"Ele"}]},
  { front:"ו", back:"Vav", examples:[{word:"וְ",translit:"Ve",meaning:"E"},{word:"מִצְוָה",translit:"Mitzvá",meaning:"Mandamento"},{word:"דָּוִד",translit:"David",meaning:"Davi"}]},
  { front:"ז", back:"Zayin", examples:[{word:"זָהָב",translit:"Zahav",meaning:"Ouro"},{word:"זֶה",translit:"Zeh",meaning:"Este"},{word:"זָכָר",translit:"Zachar",meaning:"Masculino"}]},
  { front:"ח", back:"Chet", examples:[{word:"חַיִּים",translit:"Chayim",meaning:"Vida"},{word:"חֶסֶד",translit:"Chesed",meaning:"Misericórdia"},{word:"רוּחַ",translit:"Ruach",meaning:"Espírito"}]},
  { front:"ט", back:"Tet", examples:[{word:"טוֹב",translit:"Tov",meaning:"Bom"},{word:"טָהוֹר",translit:"Tahor",meaning:"Puro"},{word:"מַטֶּה",translit:"Mateh",meaning:"Vara"}]},
  { front:"י", back:"Yod", examples:[{word:"יָד",translit:"Yad",meaning:"Mão"},{word:"יָם",translit:"Yam",meaning:"Mar"},{word:"יְהוָה",translit:"Adonai",meaning:"Senhor"}]},
  { front:"כ", back:"Chaf", examples:[{word:"בָּכָה",translit:"Bakhá",meaning:"Chorou"},{word:"אָכַל",translit:"Akhál",meaning:"Comeu"},{word:"שָׁכַב",translit:"Shakháv",meaning:"Deitou-se"}]},
  { front:"כּ", back:"Kaf", examples:[{word:"כָּל",translit:"Kol",meaning:"Tudo"},{word:"כִּי",translit:"Ki",meaning:"Porque"},{word:"כֹּהֵן",translit:"Kohen",meaning:"Sacerdote"}]},
  { front:"ך", back:"Chaf Sofit", examples:[{word:"מֶלֶךְ",translit:"Melech",meaning:"Rei"},{word:"דֶּרֶךְ",translit:"Derech",meaning:"Caminho"},{word:"בָּרוּךְ",translit:"Baruch",meaning:"Bendito"}]},
  { front:"ל", back:"Lamed", examples:[{word:"לֵב",translit:"Lev",meaning:"Coração"},{word:"לֹא",translit:"Lo",meaning:"Não"},{word:"לַיְלָה",translit:"Layla",meaning:"Noite"}]},
  { front:"מ", back:"Mem", examples:[{word:"מַיִם",translit:"Mayim",meaning:"Água"},{word:"מֶלֶךְ",translit:"Melech",meaning:"Rei"},{word:"מָקוֹם",translit:"Makom",meaning:"Lugar"}]},
  { front:"ם", back:"Mem Sofit", examples:[{word:"שָׁלוֹם",translit:"Shalom",meaning:"Paz"},{word:"יוֹם",translit:"Yom",meaning:"Dia"},{word:"שֵׁם",translit:"Shem",meaning:"Nome"}]},
  { front:"נ", back:"Nun", examples:[{word:"נָבִיא",translit:"Navi",meaning:"Profeta"},{word:"נֵר",translit:"Ner",meaning:"Lâmpada"},{word:"נָתַן",translit:"Natan",meaning:"Deu"}]},
  { front:"ן", back:"Nun Sofit", examples:[{word:"בֵּן",translit:"Ben",meaning:"Filho"},{word:"זָקֵן",translit:"Zaken",meaning:"Ancião"},{word:"כֹּהֵן",translit:"Kohen",meaning:"Sacerdote"}]},
  { front:"ס", back:"Samekh", examples:[{word:"סֵפֶר",translit:"Sefer",meaning:"Livro"},{word:"סוּס",translit:"Sus",meaning:"Cavalo"},{word:"חֶסֶד",translit:"Chesed",meaning:"Misericórdia"}]},
  { front:"ע", back:"Ayin", examples:[{word:"עַם",translit:"Am",meaning:"Povo"},{word:"עֵץ",translit:"Etz",meaning:"Árvore"},{word:"שָׁמַע",translit:"Shama",meaning:"Ouviu"}]},
  { front:"פ", back:"Fei", examples:[{word:"רָפָא",translit:"Rafá",meaning:"Curou"},{word:"נֶפֶשׁ",translit:"Néfesh",meaning:"Alma"},{word:"יָפֶה",translit:"Yafé",meaning:"Bonito"}]},
  { front:"פּ", back:"Pe", examples:[{word:"פֶּה",translit:"Peh",meaning:"Boca"},{word:"פֹּה",translit:"Po",meaning:"Aqui"},{word:"פָּעַל",translit:"Paal",meaning:"Fez"}]},
  { front:"ף", back:"Fei Sofit", examples:[{word:"אֶלֶף",translit:"Elef",meaning:"Mil"},{word:"סוֹף",translit:"Sof",meaning:"Fim"},{word:"כָּנָף",translit:"Kanaf",meaning:"Asa"}]},
  { front:"צ", back:"Tzadi", examples:[{word:"צַדִּיק",translit:"Tsadik",meaning:"Justo"},{word:"צֹאן",translit:"Tzon",meaning:"Rebanho"},{word:"מִצְוָה",translit:"Mitzvá",meaning:"Mandamento"}]},
  { front:"ץ", back:"Tzadi Sofit", examples:[{word:"אֶרֶץ",translit:"Eretz",meaning:"Terra"},{word:"קֵץ",translit:"Ketz",meaning:"Fim"},{word:"חֵץ",translit:"Chetz",meaning:"Flecha"}]},
  { front:"ק", back:"Quf", examples:[{word:"קוֹל",translit:"Kol",meaning:"Voz"},{word:"קָדוֹשׁ",translit:"Kadosh",meaning:"Santo"},{word:"מָקוֹם",translit:"Makom",meaning:"Lugar"}]},
  { front:"ר", back:"Resh", examples:[{word:"רֹאשׁ",translit:"Rosh",meaning:"Cabeça"},{word:"רוּחַ",translit:"Ruach",meaning:"Espírito"},{word:"אֶרֶץ",translit:"Eretz",meaning:"Terra"}]},
  { front:"ש", back:"Shin", examples:[{word:"שָׁלוֹם",translit:"Shalom",meaning:"Paz"},{word:"שֵׁם",translit:"Shem",meaning:"Nome"},{word:"שָׁמַיִם",translit:"Shamayim",meaning:"Céus"}]},
  { front:"ת", back:"Thav", examples:[{word:"שַׁבָּת",translit:"Shabát",meaning:"Sábado"},{word:"אֱמֶת",translit:"Emét",meaning:"Verdade"},{word:"בַּיִת",translit:"Báyit",meaning:"Casa"}]},
  { front:"תּ", back:"Tav", examples:[{word:"תּוֹרָה",translit:"Torah",meaning:"Lei"},{word:"תָּם",translit:"Tam",meaning:"Íntegro"},{word:"תֵּן",translit:"Ten",meaning:"Dá"}]}
];

const vowelCards = [
  { front:"בַ", back:"Patach", examples:[{word:"גַּן",translit:"Gan",meaning:"Jardim"},{word:"יַד",translit:"Yad",meaning:"Mão"},{word:"חַי",translit:"Chai",meaning:"Vivo"}]},
  { front:"בָ", back:"Kamatz", examples:[{word:"אָב",translit:"Av",meaning:"Pai"},{word:"דָּבָר",translit:"Davar",meaning:"Palavra"},{word:"שָׁנָה",translit:"Shaná",meaning:"Ano"}]},
  { front:"בֶ", back:"Segol", examples:[{word:"מֶלֶךְ",translit:"Melech",meaning:"Rei"},{word:"אֶרֶץ",translit:"Eretz",meaning:"Terra"},{word:"יֶלֶד",translit:"Yeled",meaning:"Criança"}]},
  { front:"בֵ", back:"Tzeirei", examples:[{word:"בֵּן",translit:"Ben",meaning:"Filho"},{word:"שֵׁם",translit:"Shem",meaning:"Nome"},{word:"אֵשׁ",translit:"Esh",meaning:"Fogo"}]},
  { front:"בִ", back:"Chirik", examples:[{word:"כִּי",translit:"Ki",meaning:"Porque"},{word:"דִּין",translit:"Din",meaning:"Julgamento"},{word:"עִיר",translit:"Ir",meaning:"Cidade"}]},
  { front:"בֹ", back:"Cholam", examples:[{word:"קֹדֶשׁ",translit:"Kodesh",meaning:"Santidade"},{word:"כֹּל",translit:"Kol",meaning:"Tudo"},{word:"שֹׁרֶשׁ",translit:"Shoresh",meaning:"Raiz"}]},
  { front:"בוֹ", back:"Cholam Malei", examples:[{word:"שָׁלוֹם",translit:"Shalom",meaning:"Paz"},{word:"טוֹב",translit:"Tov",meaning:"Bom"},{word:"יוֹם",translit:"Yom",meaning:"Dia"}]},
  { front:"בֻ", back:"Kubutz", examples:[{word:"חֻקָּה",translit:"Chuká",meaning:"Decreto"},{word:"סֻכָּה",translit:"Suká",meaning:"Cabana"},{word:"קֻם",translit:"Kum",meaning:"Levanta"}]},
  { front:"בוּ", back:"Shuruk", examples:[{word:"רוּחַ",translit:"Ruach",meaning:"Espírito"},{word:"שׁוּב",translit:"Shuv",meaning:"Voltar"},{word:"אוּר",translit:"Ur",meaning:"Luz"}]},
  { front:"בְ", back:"Shva", examples:[{word:"בְּרֵאשִׁית",translit:"Bereshit",meaning:"No princípio"},{word:"שְׁמַע",translit:"Shmá",meaning:"Ouve"},{word:"זְמַן",translit:"Zman",meaning:"Tempo"}]},
  { front:"בֲ", back:"Chataf Patach", examples:[{word:"אֲנִי",translit:"Ani",meaning:"Eu"},{word:"חֲלוֹם",translit:"Chalom",meaning:"Sonho"},{word:"אֲדָמָה",translit:"Adamá",meaning:"Solo"}]},
  { front:"בֱ", back:"Chataf Segol", examples:[{word:"אֱמֶת",translit:"Emet",meaning:"Verdade"},{word:"אֱלֹהִים",translit:"Elohim",meaning:"Deus"},{word:"נֶאֱמָן",translit:"Neemán",meaning:"Fiel"}]},
  { front:"בֳ", back:"Chataf Kamatz", examples:[{word:"חֳלִי",translit:"Choli",meaning:"Doença"},{word:"אֳנִיָּה",translit:"Oniyá",meaning:"Navio"},{word:"צָהֳרַיִם",translit:"Tzohoráyim",meaning:"Meio-dia"}]}
];
